create table "transfers" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY key,
    "from_account_id" bigint not null,
    "to_account_id" bigint not null,
    "amount" float not null default 0,
    "created_at" timestamptz NOT NULL DEFAULT (now()),
    "updated_at" timestamptz NOT NULL DEFAULT (now()),
    "deleted_at" timestamptz
);

ALTER TABLE "transfers" ADD FOREIGN KEY ("from_account_id") REFERENCES "accounts" ("id");

ALTER TABLE "transfers" ADD FOREIGN KEY ("to_account_id") REFERENCES "accounts" ("id");

ALTER TABLE "movements" ADD COLUMN "transfer_id" bigint;

ALTER TABLE "movements" ADD FOREIGN KEY ("transfer_id") REFERENCES "transfers" ("id");