CREATE TABLE "users" (
  "id" BIGSERIAL PRIMARY KEY,
  "uuid" uuid NOT NULL DEFAULT (gen_random_uuid()),
  "username" varchar NOT NULL,
  "email" varchar NOT NULL,
  "name" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  "deleted_at" timestamptz
);

ALTER TABLE public.users ADD CONSTRAINT users_unique_username UNIQUE (username);
ALTER TABLE public.users ADD CONSTRAINT users_unique_email UNIQUE (email);

CREATE TABLE "credentials" (
  "id" bigserial PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "password" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  "deleted_at" timestamptz
);

ALTER TABLE "credentials" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

CREATE TABLE "account_types" (
  "id" BIGSERIAL PRIMARY KEY,
  "text" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  "deleted_at" timestamptz
);

COMMENT ON TABLE "account_types" IS 'Account types are used to categorize accounts as movement account, credit card account, ...';

INSERT INTO "account_types" ("id", "text") VALUES (1, 'deposit');
INSERT INTO "account_types" ("id", "text") VALUES (2, 'credit card');
INSERT INTO "account_types" ("id", "text") VALUES (3, 'savings');

CREATE TABLE "accounts" (
  "id" BIGSERIAL PRIMARY KEY,
  "uuid" uuid NOT NULL DEFAULT (gen_random_uuid()),
  "name" varchar not null,
  "owner_id" bigint not null,
  "account_type_id" bigint not null,
  "balance" float not null default 0,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  "deleted_at" timestamptz
);

ALTER TABLE "accounts" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id");

ALTER TABLE "accounts" ADD FOREIGN KEY ("account_type_id") REFERENCES "account_types" ("id");

CREATE TABLE "movements" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY key,
    "uuid" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "account_id" bigint not null,
    "amount" float not null default 0,
    "description" varchar not null,
    "validated" boolean not null default false ,
    "created_at" timestamptz NOT NULL DEFAULT (now()),
    "updated_at" timestamptz NOT NULL DEFAULT (now()),
    "deleted_at" timestamptz
);

ALTER TABLE "movements" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");
