// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID            int64        `json:"id"`
	Uuid          uuid.UUID    `json:"uuid"`
	Name          string       `json:"name"`
	OwnerID       int64        `json:"owner_id"`
	AccountTypeID int64        `json:"account_type_id"`
	Balance       float64      `json:"balance"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	DeletedAt     sql.NullTime `json:"deleted_at"`
}

// Account types are used to categorize accounts as movement account, credit card account, ...
type AccountType struct {
	ID        int64        `json:"id"`
	Text      string       `json:"text"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Credential struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	Password  string       `json:"password"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Movement struct {
	ID          int64         `json:"id"`
	Uuid        uuid.UUID     `json:"uuid"`
	AccountID   int64         `json:"account_id"`
	Amount      float64       `json:"amount"`
	Description string        `json:"description"`
	Validated   bool          `json:"validated"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
	DeletedAt   sql.NullTime  `json:"deleted_at"`
	TransferID  sql.NullInt64 `json:"transfer_id"`
}

type Transfer struct {
	ID            int64        `json:"id"`
	FromAccountID int64        `json:"from_account_id"`
	ToAccountID   int64        `json:"to_account_id"`
	Amount        float64      `json:"amount"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	DeletedAt     sql.NullTime `json:"deleted_at"`
}

type User struct {
	ID        int64        `json:"id"`
	Uuid      uuid.UUID    `json:"uuid"`
	Username  string       `json:"username"`
	Email     string       `json:"email"`
	Name      string       `json:"name"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}
